repos:
  - repo: https://github.com/lycheeverse/lychee.git
    rev: v0.18.0
    hooks:
      - id: lychee
        # Optionally include additional CLI arguments
        args: ["--no-progress", "--exclude", "file://"]
