name: Install Tools & Dependencies
description: Installs pnpm, Node.js & package dependencies

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.13.1'
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Cache pnpm store
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - uses: actions/cache@v4
      name: Cache node_modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml') }}

    - name: 'Verify Tools Installation'
      shell: bash
      run: |
        command -v node || exit 1
        command -v pnpm || exit 1
        node -v
        pnpm -v

    - name: Install dependencies
      shell: bash
      run: pnpm install