name: Links

on: [push, pull_request]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache lychee
        id: cache-lychee
        uses: actions/cache@v2
        with:
          path: .lycheecache
          key: cache-lychee-${{ hashFiles('**/*') }}
          restore-keys: |
            cache-lychee-

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2.2.0
        with:
          args: --base . --cache --max-cache-age 1d . --max-redirects 10 --max-retries 5 --user-agent Chrome/51.0.2704.103 Safari/537.36
          format: markdown
          jobSummary: true
          output: lychee/out.md
          fail: true
          failIfEmpty: true
          debug: false

      - name: Upload lychee output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lychee-output
          path: lychee/out.md
