name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Tools & Dependencies
        uses: ./.github/actions/node

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run Check
        run: pnpm run check

      - name: Run tests
        working-directory: packages/ascii-progress-bar
        run: pnpm test

      - name: Build package
        working-directory: packages/ascii-progress-bar
        run: pnpm build

      - name: Build docs
        run: pnpm build
